# Using bash on the servers
# Keep the minimal

# Fuzzy search over Debian packages...
alias apt_search='apt-cache pkgnames | fzf --multi --cycle --reverse --preview "apt-cache show {1}" --preview-window=:57%:wrap:hidden --bind=space:toggle-preview | xargs -ro sudo apt install'

# PATH="~/apps/spark-3.4.4:$PATH"

# . "$HOME/.local/share/../bin/env"

# Keeping ssh startup config in .bashrc means I do not have to use ZSH on the servers
#
if ! pgrep -x ssh-agent >/dev/null; then
	eval "$(ssh-agent -s)" >/dev/null
	ssh-add ~/.ssh/f_github 2>/dev/null
fi
