[[ -r ~/Repos/znap/znap.zsh ]] ||
  git clone --depth 1 -- https://github.com/marlonrichert/zsh-snap.git ~/Repos/znap
source ~/Repos/znap/znap.zsh

source ~/.bashrc

znap source zsh-users/zsh-autosuggestions
znap source dbalatero/fast-syntax-highlighting
znap source ohmyzsh/ohmyzsh plugins/direnv


source $HOME/.config/broot/launcher/bash/br

# znap eval rustup completions zsh > ~/.zfunc/_rustup
if [ -z "$HISTFILE" ]; then
	HISTFILE=$HOME/.zsh_history
fi
HISTSIZE=10000
SAVEHIST=10000

setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt inc_append_history
setopt share_history # share command history data

# necessary - otherwise ssh-agent has to be loaded manually
# zstyle :omz:plugins:ssh-agent identities ~/.ssh/f_github
# znap source ohmyzsh/ohmyzsh plugins/ssh-agent

# https://github.com/marlonrichert/zsh-snap/issues/163
# init starship
# znap eval _starship 'starship init zsh --print-full-init'
# znap prompt starship

znap prompt sindresorhus/pure

# znap eval _pyenv-init "$(pyenv virtualenv-init -)"
# znap eval _direnv-hook "$(direnv hook zsh)"

setopt extended_glob


# alias music_dl="/Users/s1//projects/music/.venv/bin/python $HOME/projects/music/music/download/cli.py" # requires quotes
alias music_process="/Users/s1/projects/music/.venv/bin/python /Users/s1/projects/music/music/process/cli.py" # requires quotes

# Must be present for pyenv to work
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
# eval "$(pyenv virtualenv-init -)" # Optional, but good practice if using Venvs


function mkenv() {
    rm -rf ./.venv && \
    python -m venv ./.venv && \
    . ./.venv/bin/activate && \
    python -m ensurepip --upgrade && \
    pip install --upgrade setuptools
}


# ~/.local/bin is not on $PATH on OSX or Linux (OpenSUSE, Debian, Ubuntu)
# in rare cases, ~/.local/bin is used as a copy destination for manually compiled apps
# some rust and haskell apps I've used compile and copy the binary to this location
# Therefore, add custom script directory from the repo onto Path
# Instead of symlinking REPO/bin -> $HOME/.local/bin
export PATH="$PATH:$HOME/dot/bin/src"
