[[ -r ~/Repos/znap/znap.zsh ]] ||
  git clone --depth 1 -- https://github.com/marlonrichert/zsh-snap.git ~/Repos/znap
source ~/Repos/znap/znap.zsh

source ~/.bashrc

znap source zsh-users/zsh-autosuggestions
znap source dbalatero/fast-syntax-highlighting
znap source ohmyzsh/ohmyzsh plugins/direnv

# znap eval rustup completions zsh > ~/.zfunc/_rustup


# necessary - otherwise ssh-agent has to be loaded manually
# zstyle :omz:plugins:ssh-agent identities ~/.ssh/f_github
# znap source ohmyzsh/ohmyzsh plugins/ssh-agent

# https://github.com/marlonrichert/zsh-snap/issues/163
# init starship
# znap eval _starship 'starship init zsh --print-full-init'
# znap prompt starship

znap prompt sindresorhus/pure

# znap eval _pyenv-init "$(pyenv virtualenv-init -)"
# znap eval _direnv-hook "$(direnv hook zsh)"

setopt extended_glob


eval "$(uv generate-shell-completion zsh)" # this part can be made bash compatible.
