#!/run/current-system/sw/bin/bash
#
##!/home/f1/.nix-profile/bin/bash

here=$(dirname $(readlink -f $0))
screen_size=${screen_size:-800x600}
xdisplay=${xdisplay:-:1}
log_level=${log_level:-info}
app=${app:-$(python -c "from libqtile.utils import guess_terminal; print(guess_terminal())")}
if [[ -z $python ]]; then
    python=python3
fi
Xephyr +extension randr -screen ${screen_size} ${xdisplay} -ac &
xephyr_pid=$!
(
  sleep 1
  env display=${xdisplay} qtile_xephyr=1 ${python} /nix/store/6g1p91qzm0gmx0bncp2fh5lla475ybli-python3.9-qtile-0.18.0/bin/qtile start -l ${log_level} $@ &
  qtile_pid=$!
  env display=${xdisplay} ${app} &
  wait $qtile_pid
  kill $xephyr_pid
)
