#!/usr/bin/bash
#
# Run after main homebrew install
brew_install rustup
rustup-init -y
source $HOME/.cargo/env

brew install pyenv
pyenv install -s 3.11.0
pyenv global 3.11.0
pip install poetry
# need to restart terminal here, maybe source both zsh files again?
source ~/.zshrc
source ~/.zshenv

# brew services start postgresql@14
#
