- defaults:
    link:
      create: true
      relink: true

# - clean: ['~', '~/.config']

- link:
    ~/.gitconfig:
    ~/.zprofile:
    ~/.xinitrc:
    ~/.zshenv:
    ~/.zshrc:
    ~/.gnupg/gpg-agent.conf: ~/dot/gnupg/gpg-agent.conf
    ~/.config/aconfmgr:
    ~/.config/dunst:
    ~/.config/kitty:
    ~/.config/picom:
    ~/.config/the-way:
    ~/.config/xplr:
    ~/.config/gita:
    ~/.config/qtile:
    ~/.config/vlc:
    ~/.config/lazygit:
    ~/.config/pet:
    ~/.config/systemd:
    ~/.config/ghorg:
    ~/.config/tmux:
    ~/.config/gobang:
    ~/.config/direnv:
    ~/.config/nvim:
    ~/.config/flavours:
    ~/.config/kmonad:
    ~/.config/i3:
    ~/.config/qutebrowser:
    ~/.config/starship.toml: ~/dot/starship.toml
    ~/.i3/i3-resurrect: ~/dot/i3/resurrect
    ~/.config/herbstluftwm: ~/dot/herbstluftwm
    ~/.config/polybar:
    ~/.config/rofi:
    ~/.themes:
    ~/.config/bat:
    ~/.config/sway:
    ~/.config/kanshi:
    ~/.config/waybar:
    ~/.config/promnesia:
    ~/.config/sgsync:
    ~/.config/tridactyl:

    ~/.local/share/nemo: 
      force: true
      path: ~/dot/nemo

    ~/repos/packer-fork: ~/dev/packer-fork

    ~/.mozilla/native-messaging-hosts/com.fhill2.browser_integration.json: ~/dev/app/browser_integration/native/browser_integration.json
    ~/.local/bin/browser_integration: ~/dev/app/browser_integration/native/browser_integration
    ~/dev/bin/fuzzy/fzf_buku: ~/dev/app/browser_integration/fzf_buku

    ~/.config/chromium/Default: ~/data/chromium-profile

    ~/.local/share/fonts: ~/data/fonts  
    ~/.local/share/applications/code.desktop: ~/dot/desktop/code.desktop 
    ~/.local/share/applications/discord.desktop: ~/dot/desktop/discord.desktop 
    ~/dev/bin/f_nvimpager: ~/dev/app/f_nvimpager/f_nvimpager
    ~/repos/packer: ~/.local/share/nvim/site/pack/packer

    ~/.local/lib/python3.10/site-packages/f: ~/dev/lib/f

    ~/dot/nvim-dropdown/lua: ~/dot/nvim/lua

    ~/a/python/user: ~/.local/lib/python3.10/site-packages
    ~/a/python/system: /usr/lib/python3.10/site-packages    

    ~/dev/bin/kvm: ~/dev/app/kvm/kvm.py
    ~/dev/bin/looking-glass-client: 
      if: '[ `hostname` = arch-desk ]'
      path: ~/dev/app/looking-glass-b5-rc1/client/build/looking-glass-client

    
- create:
    ~/.config:
    ~/logs:
    ~/Desktop:
    ~/Downloads:

# - shell:
  # - [sudo cp ~/dot/systemd/user/kvm.service /usr/lib/systemd/system/kvm.service, copy kvm systemd service file as you cant symlink service files]



  
