- defaults:
    link:
      create: true
      relink: true
      force: true


- link:
    /etc/pacman.d/hooks/50-bootbackup.hook: /home/f1/dev/sys/50-bootbackup.hook 
    /etc/xdg/reflector/reflector.conf: /home/f1/dev/sys/reflector.conf 
    /etc/snapper/configs/root: /home/f1/dev/sys/snapper-root 
    /etc/udev/rules.d/90-backlight.rules: /home/f1/dev/sys/90-backlight.rules
    /etc/kmonad/config.kbd: /home/f1/dot/kmonad/config.kbd
    /etc/sysconfig/ntpd: /home/f1/dev/sys/ntpd
- create:
    /etc/pacman.d/hooks:
