- defaults:
    link:
      create: true
      relink: true

- link:
    ~/a/fuzzy/skim: ~/dev/app/skim
    ~/a/fuzzy/fuzzy: ~/dev/app/fuzzy
    ~/a/fuzzy/scripts: ~/dev/cl/shell/scripts
    ~/a/fuzzy/sniprun: ~/dev/cl/rust/sniprun
    ~/a/fuzzy/logs: ~/logs
