

-- local awful = require"awful"
-- local dynamite = require"dynamite"
-- local mycustomtilelayout = dynamite {
--        {
--            {
--                command = "kitty",
--                widget = dynamite.widget.spawn,
--            },
--            max_elements = 1,
--            priority     = 3,
--            layout       = dynamite.layout.ratio.vertical
--        },
--        {
--            {
--                command = "kitty",
--                widget = dynamite.widget.spawn,
--            },
--            reflow       = true,
--            max_elements = 3,
--            priority     = 1,
--            layout       = dynamite.layout.ratio.vertical
--        },
--        layout = dynamite.layout.ratio.horizontal
--    }
