
# author's dotfiles https://github.com/Misterio77/dotfiles/blob/sway/home/.config/flavours/config.toml

# multiple templates
[[item]]
file = '~/.config/rofi/themes/colors.rasi'
template = 'rofi'
subtemplate = 'colors'
rewrite = true

# single template
[[item]]
file = '~/.config/polybar/colors.ini'
template = 'polybar'
subtemplate = 'custom'
hook = 'bash ~/.config/polybar/launch.sh'
rewrite = true


# single template
[[item]]
file = '~/.config/kitty/current-theme.conf'
template = 'kitty'
subtemplate = 'default-256'
rewrite = true



# https://github.com/Misterio77/base16-gtk-flatcolor
# notes on  how to reload gtk apps without restarting
[[item]]
file = "~/.themes/FlatColor/colors3"
template = "gtk-flatcolor"
subtemplate = "gtk-3"
rewrite = true
hook = "gsettings set org.gnome.desktop.interface gtk-theme FlatColor"
# hook = "gsettings set org.gnome.desktop.interface gtk-theme dummy && gsettings set org.gnome.desktop.interface gtk-theme FlatColor"

[[item]]
file = "~/.themes/FlatColor/colors2"
template = "gtk-flatcolor"
subtemplate = "gtk-2"
rewrite = true



[[item]]
file = "~/dot/nvim/lua/plugin/base16.lua"
template = "nvim"
rewrite = true

# import colours into python custom scripts so scripts like sway_print_tree for i3status-rs can use the colors
[[item]]
file = "~/dev/lib/futil.py"
template="python"
rewrite = false





# MASTER
### foreground / background / shades
# background = base00
# bglight = base01
# bgselect = base02
# comment = base03
# fgdark = base04 # - focused_inactive
# foreground = base05
# fglighter = base06
# bglighter = base07


# colors that stay somewhat consistent across themes
# red = base08
# orange = base09
# yellow = base0A
# green = base0B
# cyan = base0C
# blue = base0D
# magenta = base0E
# purple = base0F - this is deprecated, varies wildly between themes, chances are it wont be the color purple



# https://github.com/chriskempson/base16/blob/main/styling.md
# base00 - Default Background
# base01 - Lighter Background (Used for status bars, line number and folding marks)
# base02 - Selection Background
# base03 - Comments, Invisibles, Line Highlighting
# base04 - Dark Foreground (Used for status bars)
# base05 - Default Foreground, Caret, Delimiters, Operators
# base06 - Light Foreground (Not often used)
# base07 - Light Background (Not often used)
# base08 - Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
# base09 - Integers, Boolean, Constants, XML Attributes, Markup Link Url
# base0A - Classes, Markup Bold, Search Text Background
# base0B - Strings, Inherited Class, Markup Code, Diff Inserted
# base0C - Support, Regular Expressions, Escape Characters, Markup Quotes
# base0D - Functions, Methods, Attribute IDs, Headings
# base0E - Keywords, Storage, Selector, Markup Italic, Diff Changed
# base0F - Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
