[[conn]]
type = "sqlite"
path = "/home/f1/.local/share/nvim/file_frecency.sqlite3"

[[conn]]
type = "sqlite"
path = "/home/f1/.local/share/promnesia/promnesia.sqlite"

[[conn]]
type = "sqlite3"
path = "/home/f1/.mozilla/firefox/yxegqb9w.default-nightly/places.sqlite"
