#!/usr/bin/env sh


HOST="$(hostname)"


PSDIR=$(dirname "$0") # --> script dir's parent
root="$(git -C "$PSDIR" rev-parse --show-toplevel)" # find git root from PSDIR
_symlink="$root/shared/bin/src/_symlink"


$_symlink $root/shared/config/nvim ~/.config/nvim
$_symlink $root/shared/config/git/gitconfig ~/.gitconfig
$_symlink $root/shared/config/git/gitignore ~/.gitignore
$_symlink $root/shared/config/broot ~/.config/broot
$_symlink $root/shared/config/xplr ~/.config/xplr
$_symlink $root/shared/config/tmux ~/.config/tmux
$_symlink $root/shared/config/starship.toml ~/.config/starship.toml
mkdir -p ~/.config/bat
$_symlink $root/shared/config/bat/config ~/.config/bat/config # this is a file
# $_symlink config/lazygit/config.yml ~/Library/Application\ Support/lazygit/config.yml
$_symlink $root/shared/config/git/gitattributes ~/.gitattributes

$_symlink $root/debian/config/shell/zshrc ~/.zshrc
$_symlink $root/debian/config/shell/zprofile ~/.zprofile
$_symlink $root/debian/config/shell/profile_debian ~/.profile
$_symlink $root/debian/config/systemd/user ~/.config/systemd/user
$_symlink $root/debian/config/sway ~/.config/sway
$_symlink $root/debian/config/kitty ~/.config/kitty

# modified desktop files
$_symlink $root/debian/config/desktop/obsidian-wayland.desktop ~/.local/share/applications/obsidian-wayland.desktop
$_symlink $root/debian/config/desktop/discord-wayland.desktop /usr/share/applications/discord-wayland.desktop
# $_symlink $root/debian/config/desktop/obsidian-wayland.desktop ~/.local/share/applications/obsidian-wayland.desktop



if [ "$HOST" = "f-server-g" ]; then
# https://github.com/jtroo/kanata/blob/main/docs/setup-linux.md
  $_symlink "$root/debian/config/kanata" ~/.config/kanata
  $_symlink "$root/debian/config/init.d/kanata" /etc/init.d/kanata
  $_symlink "$root/debian/config/kanata/99-input.rules" /etc/udev/rules.d/99-input.rules

fi

$_symlink "$root/debian/config/interfaces_$HOST" /etc/network/interfaces
# sudo systemctl restart networking 

# QMK Keyboard - Prevent Permission Denied on qmk console
if [ "$HOST" = "f-server" ]; then
  # qmk
  $_symlink "$root/debian/config/qmk/udev/92-viia.rules" /etc/udev/rules.d/92-viia.rules
fi

