#!/usr/bin/env sh

HOST="$(hostname)"

PSDIR=$(dirname "$0")                               # --> script dir's parent
root="$(git -C "$PSDIR" rev-parse --show-toplevel)" # find git root from PSDIR
_symlink="$root/shared/bin/src/_symlink"

# TODO:
# setup a better way to symlink scripts into a directory on PATH
# bin files
# TODO:
# take out auto running as sudo in the _symlink script
# and add sudo to each line that needs it

mkdir -p $HOME/apps
mkdir -p $HOME/git
mkdir -p $HOME/projects
mkdir -p $HOME/Desktop
mkdir -p $HOME/.config

mkdir -p $HOME/.local                       # dir does not exist on a fresh debian install
$_symlink $root/debian/bin/src ~/.local/bin # dont know why this is perm denied with _symlink

if [ "$HOST" = "f-desktop" ]; then
	$_symlink $root/debian/bin/src/start_screenshare ~/.local/bin/start_screenshare
	$_symlink $root/debian/bin/src/stop_screenshare ~/.local/bin/stop_screenshare
fi

$_symlink $root/shared/config/nvim ~/.config/nvim
$_symlink $root/shared/config/git/gitconfig ~/.gitconfig
$_symlink $root/shared/config/git/gitignore ~/.gitignore
$_symlink $root/shared/config/broot ~/.config/broot
$_symlink $root/shared/config/xplr ~/.config/xplr
$_symlink $root/shared/config/tmux ~/.config/tmux
$_symlink $root/shared/config/starship.toml ~/.config/starship.toml
mkdir -p ~/.config/bat
$_symlink $root/shared/config/bat/config ~/.config/bat/config # this is a file
# $_symlink config/lazygit/config.yml ~/Library/Application\ Support/lazygit/config.yml
$_symlink $root/shared/config/git/gitattributes ~/.gitattributes

$_symlink $root/debian/config/shell/zshrc ~/.zshrc
$_symlink $root/debian/config/shell/zprofile ~/.zprofile
$_symlink $root/debian/config/profile_debian ~/.profile
$_symlink $root/debian/config/systemd/user ~/.config/systemd/user
$_symlink $root/debian/config/sway ~/.config/sway
$_symlink $root/debian/config/kitty ~/.config/kitty

# modified desktop files
$_symlink $root/debian/config/desktop/obsidian-wayland.desktop ~/.local/share/applications/obsidian-wayland.desktop
$_symlink $root/debian/config/desktop/discord-wayland.desktop ~/.local/share/applications/discord-wayland.desktop
$_symlink $root/debian/config/desktop/ib-gateway-wayland.desktop ~/.local/share/applications/ib-gateway-wayland.desktop
$_symlink $root/debian/config/desktop/spacefm-wayland.desktop ~/.local/share/applications/spacefm-wayland.desktop

if [ "$HOST" = "f-server" ]; then
	# https://github.com/jtroo/kanata/blob/main/docs/setup-linux.md
	$_symlink "$root/debian/config/kanata" ~/.config/kanata
	$_symlink "$root/debian/config/init.d/kanata" /etc/init.d/kanata
	$_symlink "$root/debian/config/kanata/99-input.rules" /etc/udev/rules.d/99-input.rules
fi

if [ -f "$root/debian/config/interfaces_$HOST" ]; then
	$_symlink "$root/debian/config/interfaces_$HOST" /etc/network/interfaces
fi
# sudo systemctl restart networking

# QMK Keyboard - Prevent Permission Denied on qmk console
if [ "$HOST" = "f-desktop" ]; then
	# Note: barman does not work with symlinks
	# It does work with hard links (ln instead of ln -s)
	sudo ln "$root/debian/config/barman/basebackups.cron" /etc/cron.d/basebackups
	sudo ln "$root/debian/config/barman/f-server.conf" /etc/barman.d/f-server.conf
	# qmk
	$_symlink "$root/debian/config/qmk/udev/92-viia.rules" /etc/udev/rules.d/92-viia.rules
fi

# f-server postgres needs to override the system installed systemd service file
# to modify the PG_DATA path to the zfs dataset
# if [ "$HOST" = "f-server" ]; then
# $_symlink "$root/debian/config/systemd/postgresql_f-server.service" /usr/lib/systemd/system/postgresql.service
# fi
