#!/usr/bin/bash

#BASEDIR=$(dirname "$0")
#echo "$BASEDIR"
#r=/home/f1/dot/config/aconfmgr/syms



if [ "$EUID" -ne 0 ]; then 
  echo "Please run as root"
exit
fi


r=$(pwd)
##ln -sf $r/sudoers /etc/sudoers.d/20-fhill2
ln -sf $r/50-bootbackup.hook /etc/pacman.d/hooks/50-bootbackup.hook
ln -sf $r/reflector.conf /etc/xdg/reflector/reflector.conf
ln -sf $r/reflector.conf /etc/xdg/reflector/reflector.conf
ln -sf $r/snapper-root /etc/snapper/configs/root
