#!/bin/bash

# if no arguments are passed in, install syms only
# if [ $# = 0 ];then
#   chosen="sym"
# else
#   chosen="$1"
# fi

# deprecated parts of the main dotbot install script entrypoint


case $chosen in
  # if all is passed as first argument, install all parts of config
  "all")
      configs=("sym" "pacman" "pacman_$HOST" "cargo" "pip")
    ;;
  "pkg")
    configs=("pacman" "pacman_$HOST" "cargo" "pip") 
  ;;
  *)
      configs=("$1")
  ;;
esac

clone_dotbot_plugin() {
    USER=${1%/*} 
    REPO=${1##*/}  # retain the part after the last slash
    # if dotbot plugins does not exist, clone it
    if [ ! -d "$HOME/.dotbot/$REPO" ]; then
      git clone "https://github.com/$USER/$REPO" "$HOME/.dotbot/$REPO"
    fi
}

# install dotbot plugins because I don't want to add dotbot and the plugins as submodules to dotfiles
clone_dotbot_plugin "fhill2/dotbot-sudo"


# clone_dotbot_plugin "fhill2/dotbot-yay"
clone_dotbot_plugin "alexcormier/dotbot-rust"
clone_dotbot_plugin "wonderbeyond/dotbot-if"
clone_dotbot_plugin "sobolevn/dotbot-pip"
clone_dotbot_plugin "delidb/dotbot-golang"

# ========== dotbot-pacaur ==========
# 26 Mar 2023: still needs fork modifications to return the correct path to dotbot
# Oct 2022: with dotbot installed through yay or pip --user, dotbot-sudo looks for dotbot binary at /usr/lib/python3.10/site-packages/bin/dotbot, or ~/.local/lib/python3.10/site-packages, and the binary is not located there. this has been fixed in my forked version.
# ===================================

# dotbot-yay -> does NOT check if the package is installed before installing. useless.
# dotbot-pacaur -> not using as pacaur project is currently unmaintained

# ========== dotbot-pacaur ==========
# it does install official and aur packages fully automated, however it requires pacaur to be installed to install AUR packages first.
# the included dotbot-pacaur bootstrap script is broken, and there are no reliable pacaur bootstrap scripts available that I've found (oct 2022)
# ===================================

# dotbot-rust - installs with cargo install --force by default (upgrades on every run) - I want this as an option
# dotbot-paru -> does not have is_installed. is a clone of dotbot-yay

for config in "${configs[@]}"; do
"$HOME/.local/bin/dotbot" -v -d "${BASEDIR}" \
  -c "dotbot/$config.yaml" \
  -p ~/.dotbot/dotbot-if/if.py \
  -p ~/.dotbot/dotbot-sudo/sudo.py \
  -p ~/.dotbot/dotbot-rust/rust.py \
  -p ./dotbot/yay.py \
  -p ~/.dotbot/dotbot-pip/pip.py \
  -p ~/.dotbot/dotbot-golang/go.py

done
