#!/usr/bin/env bash

# ========== OSX - Install on Laptop & Studio Comp  ==========

source _installer.sh

dotheader "Setting up devtools for Studio and Laptop..."



install_git() {
  install_package "git"
  brew_install diff-so-fancy
  brew_tap_install jesseduffield/lazygit
  brew_install lazygit
  symlink_dotfile config/git/gitattributes ~/.gitattributes
  symlink_dotfile config/git/gitconfig ~/.gitconfig
  symlink_dotfile config/git/gitignore ~/.gitignore
}
install_git

install_bat() {
	brew_install bat
	mkdir -p ~/.config/bat
	symlink_dotfile bat/config ~/.config/bat/config
}
install_bat


install_package kitty
symlink_dotfile config/kitty ~/.config/kitty

install_package starship
symlink_dotfile config/starship ~/.config/starship




# a secrets workflow:
# gnupg -> installed via package manager
# gpg private key -> stored in bw, unsynced
# password store -> synced privately using syncthing
install_package gnupug

brew_install coreutils
install_package trash
install_package fd
install_package jq
install_package direnv
install_package "bitwarden" # electron bitwarden GUI - CLI installed via npm
install_package pet
install_package sl
install_package wget


# ack is a grep-like source code search tool.
brew_install ack 
brew_install gnu-tar
brew_install ripgrep

brew_install gnu-sed # some nvim app needs this on osx
brew_install zoxide
brew_install "colordiff"
brew_install "fzf"
brew_install "go"

brew_install "mas"
brew_install "nmap"
brew_install "rename"
brew_install "ripgrep"
brew_install "rsync"
brew_install "terminal-notifier"
brew_install "rar" # <-- unrar moved due to licensing issues




# pytower deps
brew_tap_install "homebrew/cask"
brew_install 'poetry'

brew_install showkey


brew_cask_install 'tailscale'
brew_install 'tailscale' # for tailscale debugging

brew_install 'act'

