#!/usr/bin/env bash
source _installer.sh
# ========== OSX - Install on Laptop  ==========

cargo_install proximity-sort

install_package flavours
symlink_dotfile config/flavours ~/.config/flavours

install_package xplr
symlink_dotfile config/xplr ~/.config/xplr

install_package broot
symlink_dotfile config/broot ~/.config/broot

# pytower deps
brew_tap_install "esolitos/ipa"
brew_tap_install "yulrizka/tap"
brew_install 'pre-commit'
brew_install 'ta-lib'
# pytower - reading parquet files
brew_install parquet-cli

brew_install node
brew_install yarn
brew_install npm
brew_install neofetch

# pytower
brew install --cask teamviewer

# pytower - for IB Gateway connection testing
# brew install docker provides terminal only, and I have not configured it to start the daemon
# brew install --cask docker <- the GUI runs the docker daemon on start
brew install --cask docker-desktop

# checkout PR and more
brew install gh
brew install ipython

# javascript typescript react formatters
brew install prettierd
brew install printd
