#!/usr/bin/env bash


current_dir=$(pwd)
pushd $current_dir
cd ../config/launchd

agents=(*.plist)

for agent in "${agents[@]}"
do
    ln -s "$PWD/$agent" ~/Library/LaunchAgents
    launchctl load ~/Library/LaunchAgents/$agent
done


popd
