#!/usr/bin/env bash

source _installer.sh
symlink_all_within "$HOME/dot/config/launchd" "$HOME/Library/LaunchAgents"


# current_dir=$(pwd)
# pushd $current_dir
# cd ../config/launchd
#
# agents=(*.plist)
#
# for agent in "${agents[@]}"
# do
#     ln -s "$PWD/$agent" ~/Library/LaunchAgents
#     launchctl load ~/Library/LaunchAgents/$agent
# done
#
#
# popd
