#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager
require_installer fonts
require_installer ruby
require_installer python
require_installer node

function install_packer_nvim() {
	local location="$HOME/.local/share/nvim/site/pack/packer/start/packer.nvim"

	if [ ! -d "$location" ]; then
		dotsay "@b@blue[[+ Installing packer.nvim]]"
		git clone --depth 1 https://github.com/wbthomason/packer.nvim "$location"
	fi
}

function install_neovim_debian() {
	if ! apt_is_installed "neovim"; then
		sudo add-apt-repository -y ppa:neovim-ppa/stable
		sudo apt-get -y update
		apt_install neovim

		sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
		sudo update-alternatives --config vi
		sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
		sudo update-alternatives --config vim
		sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
		sudo update-alternatives --config editor
	fi
}

function install_neovim_mac() {
	if ! brew_is_tapped "neovim/neovim"; then
		brew_tap neovim/neovim
	fi

	brew_install neovim --HEAD
}

function install_neovim() {
	if is_macos; then
		install_neovim_mac
	elif is_debian; then
		install_neovim_debian
	elif is_arch; then

	fi
	symlink_dotfile nvim ~/.config/nvim
	# symlink_absolute_dotfile ~/dot/snippets ~/.local/share/nvim/site/pack/packer/start/my_snippets
}









dotheader "Setting up Neovim..."

brew_install luajit
install_packer_nvim

#install_ruby_neovim
#install_typescript_language_server
#install_write_good
install_neovim
setup_neovim_config
install_tern
install_vim_node_rpc
ensure_plugin_directory
install_neovim_plugins
install_rust
install_proximity_sort
install_stylua
install_bat
install_vscode_language_servers
install_yaml_language_server
