#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

install_ext4fuse() {
# to read/write ext4 drives, homebrew macfuse, and ext4fuse is needed.
# https://github.com/gerard/ext4fuse/issues/66#issuecomment-1435992847
# homebrew cannot install ext4fuse on osx anymore.
# this installs ext4fuse from source...

pushd .
git clone https://github.com/gerard/ext4fuse.git ~/.apps/ext4fuse
cd ~/.apps/ext4fuse
make
# sudo ln -s ext4fuse /usr/local/bin/ext4fuse
symlink_relative_dotfile ext4fuse /usr/local/bin/ext4fuse
# sudo -u root sh -c 'symlink_dotfile ext4fuse /usr/local/bin/ext4fuse'
popd
# sudo ./ext4fuse /dev/disk4 ~/ext4_mount -o allow_other 
}
install_ext4fuse