#!/usr/bin/env bash
source _installer.sh

# this could probably be added to bootstrap
# needs to run before any plugin .pkg installs, otherwise they fail
sudo softwareupdate --install-rosetta


brew install --cask tailscale
brew install discord
brew install bitwig-studio
brew install the-unarchiver
brew install --cask obsidian
syncthing
kitty

symlink_dotfile 