#!/usr/bin/env bash
source _installer.sh

# this could probably be added to bootstrap
# needs to run before any plugin .pkg installs, otherwise they fail
sudo softwareupdate --install-rosetta


brew install --cask tailscale
brew install discord
brew install bitwig-studio
brew install the-unarchiver
brew install --cask obsidian
syncthing
kitty

symlink_dotfile config/qobuz-dl/config.ini ~/.config/qobuz-dl/config.ini
# could install qobuz-dl globally and demucs



# demucs deps
brew install ffmpeg
brew install sound-touch

# temporary, otherwise mason nvim errors as it installs packages with npm
brew install npm
brew install splice
brew install jdownloader

# make symbolic link in osx services menu
# to create symlinks to libraries manually
brew install symboliclinker

