#!/usr/bin/env bash


install_syncthing() {
  install_package syncthing
  # syncthing needs to be started after install
  brew services start syncthing
}


# ~/.config/syncthing/config.xml
# change <address></address> to 0.0.0.0
# this allows connecting to show syncthing web gui over LAN
# cant sync this file as it contains device IDs
# and cba to script with aug or sed
# ```xml
# <gui enabled="true" tls="false" debugging="false">
# <address>0.0.0.0:8384</address>
# <apikey>Po7cHpbLHs7sjRuNRJkJXQG2gxstbuxC</apikey>
# <theme>default</theme>
# </gui>
# ```