# - link:
#     ~/cl/shell/repos: ~/repos/shell
#     ~/cl/python/kitty_kittens: ~/repos/kitty_kittens
#     ~/cl/dot/nix: ~/repos/dotfiles_nix
#     ~/cl/dot/lua: ~/repos/dotfiles_lua

# non repo syms
# symlink nvim plugins to cl
#$HOME/.config/awesome: '$r/awesome_modules'

- git:
    ~/repos/shell/nnn:
      url: https://github.com/jarun/nnn
    ~/repos/shell/kitty:
      url: https://github.com/kovidgoyal/kitty

    #~/repos/kitty_kittens/kitty:
    #      url: https://github.com/kovidgoyal/kitty/tree/master/kittens
    ~/repos/kitty_kittens/kitty-weechat-hints:
      url: https://github.com/GermainZ/kitty-weechat-hints
    ~/repos/kitty_kittens/vim-kitty-navigator:
      url: https://github.com/knubie/vim-kitty-navigator
    ~/repos/kitty_kittens/kitty-session:
      url: https://github.com/muchzill4/kitty-session
    ~/repos/kitty_kittens/kitty-cat:
      url: https://github.com/adi1090x/kitty-cat
    ~/repos/kitty_kittens/kitty-smart-scroll:
      url: https://github.com/yurikhan/kitty-smart-scroll
    # ~/repos/kitty_kittens/:
    #        url: https://github.com/nerdrew/kittens/blob/master/password.py
    ~/repos/dotfiles/sherubthakur:
      url: https://github.com/sherubthakur/dotfiles
    ~/repos/dotfiles/teto:
      url: https://github.com/teto/home
    ~/repos/dotfiles/notusknot:
      url: https://github.com/notusknot/dotfiles-nix
    ~/repos/dotfiles/breuerfelix:
      url: https://github.com/breuerfelix/nixos
    ~/repos/dotfiles/moletrooper:
      url: https://github.com/MoleTrooper/dotfiles
    ~/repos/dotfiles/elianiva:
      url: https://github.com/elianiva/dotfiles
    
    ~/repos/dotfiles/gf3:
      url: https://github.com/gf3/dotfiles
    ~/repos/dotfiles/jameswalmsley:
      url: https://github.com/jameswalmsley/dotfiles
    ~/repos/dotfiles/lunarvim:
      url: https://github.com/LunarVim/LunarVim
    ~/repos/dotfiles/nvchad:
      url: https://github.com/NvChad/NvChad
    ~/repos/dotfiles/conni2461:
      url: https://github.com/Conni2461/dotfiles
    ~/repos/dotfiles/tjdevries:
      url: https://github.com/tjdevries/config_manager
    ~/repos/dotfiles/weilbith:
      url: https://github.com/weilbith/dotfiles
    ~/repos/dotfiles/fdschmidt93:
      url: https://github.com/fdschmidt93/dotfiles

    ~/repos/dotfiles/junegunn:
      url: https://github.com/junegunn/dotfiles

    ~/repos/dotfiles_i3/ethanschoonover:
      url: https://github.com/altercation/dotfiles-tilingwm
    ~/repos/dotfiles_i3/thelinuxcast:
      url: https://gitlab.com/thelinuxcast/my-dots
    ~/repos/dotfiles_i3/ellathecat:
      url: https://github.com/EllaTheCat/dopamine

    ~/repos/dotfiles_herb/jan-lunge:
      url: https://github.com/wlard/dotfiles
    ~/repos/dotfiles_herb/ssh0:
      url: https://github.com/ssh0/dotfiles
    # ~/repos/dotfiles/distrotube:
      # url: https://gitlab.com/dwt1/dotfiles
    ~/repos/dotfiles_herb/scourii:
      url: https://github.com/scourii/.dotfiles


    ~/repos/rust/xplr:
      url: https://github.com/sayanarijit/xplr
    ~/repos/rust/bat:
      url: https://github.com/sharkdp/bat
    ~/repos/rust/starship:
      url: https://github.com/starship/starship
    ~/repos/rust/rustlings:
      url: https://github.com/rust-lang/rustlings
    ~/repos/rust/exa:
      url: https://github.com/ogham/exa
    ~/repos/rust/delta:
      url: https://github.com/dandavison/delta
    ~/repos/rust/spotify-tui:
      url: https://github.com/Rigellute/spotify-tui
    ~/repos/rust/coreutils:
      url: https://github.com/uutils/coreutils
    ~/repos/rust/hyperfine:
      url: https://github.com/sharkdp/hyperfine
    ~/repos/rust/navi:
      url: https://github.com/denisidoro/navi
    ~/repos/rust/the-way:
      url: https://github.com/out-of-cheese-error/the-way
    ~/repos/rust/skim:
      url: https://github.com/lotabout/skim

    #~/repos/python/pytower:
    #    url: https://github.com/ghill2/pytower_proj
    ~/repos/python/polygon-client:
      url: https://github.com/polygon-io/client-python
    ~/repos/python/polygon-client-examples:
      url: https://github.com/polygon-io/client-examples
    ~/repos/python/qtile-examples:
      url: https://github.com/qtile/qtile-examples
    ~/repos/python/qtile:
      url: https://github.com/qtile/qtile
    ~/repos/python/pyuv:
      url: https://github.com/saghul/pyuv

    # ~/repos/python/evdev/evdev-gist:
    #   url: https://gist.github.com/t184256/f4994037a2a204774ef3b9a2b38736dc
    ~/repos/python/evdev/python-evdev:
      url: https://github.com/gvalkov/python-evdev
    ~/repos/python/evdev/remappy:
      url: https://github.com/SirAeroWN/remappy
    ~/repos/python/evdev/vfio-switcher:
      url: https://github.com/CappyT/VFIO-Switcher
    ~/repos/python/evdev/libvirt-evdev:
      url: https://github.com/mciupak/libvirt-evdev
    ~/repos/python/evdev/persistent-evdev:
      url: https://github.com/aiberia/persistent-evdev
    ~/repos/python/evdev/vfio-kvm:
      url: https://github.com/dangle/akeydo
    ~/repos/python/evdev/evmapy:
      url: https://github.com/kempniu/evmapy
    ~/repos/python/evdev/uinput-keyboard-mapper:
      url: https://github.com/sebastiansam55/uinput-keyboard-mapper

    ~/repos/i3/i3:
      url: https://github.com/i3/i3
    ~/repos/i3/layout/i3-resurrect:
      url: https://github.com/JonnyHaystack/i3-resurrect
    ~/repos/i3/layout/i3-layouts:
      url: https://github.com/eliep/i3-layouts
    ~/repos/i3/layout/i3-alternating-layout:
      url: https://github.com/olemartinorg/i3-alternating-layout
    ~/repos/i3/layout/i3-clever-layout:
      url: https://github.com/talwrii/i3-clever-layout
    ~/repos/i3/i3ass:
      url: https://github.com/budlabs/i3ass
    ~/repos/i3/kitti3:
      url: https://github.com/LandingEllipse/kitti3
    ~/repos/i3/i3-wm-scripts:
      url: https://github.com/micahcc/i3-wm-scripts
    ~/repos/i3/i3-rofi-mark:
      url: https://github.com/talwrii/i3-rofi-mark
    ~/repos/i3/i3-parse:
      url: https://github.com/talwrii/i3parse
    ~/repos/i3/i3-scripts:
      url: https://github.com/xmendez/i3-scripts
    ~/repos/i3/i3scripts:
      url: https://github.com/justbuchanan/i3scripts
    ~/repos/i3/quickswitch-for-i3:
      url: https://github.com/OliverUv/quickswitch-for-i3
    ~/repos/i3/theme/i3-style:
      url: https://github.com/altdesktop/i3-style
    ~/repos/i3/i3-easyfocus:
      url: https://github.com/cornerman/i3-easyfocus
    ~/repos/i3/isblocks:
      url: https://github.com/Anachron/i3blocks
    ~/repos/i3/theme/i3wm-themer:
      url: https://github.com/stav121/i3wm-themer
    ~/repos/i3/layout/i3nator:
      url: https://github.com/pitkley/i3nator
    ~/repos/i3/i3ipc-python:
      url: https://github.com/altdesktop/i3ipc-python
    ~/repos/i3/i3-cycle:
      url: https://github.com/dustbyte/i3-cycle
      # https://github.com/EllaTheCat/dopamine/blob/master/i3files/i3-wrapper


    ~/repos/rofi/rofi:
      url: https://github.com/davatorium/rofi
    ~/repos/rofi/rofi-custom:
      url: https://github.com/adi1090x/rofi
    ~/repos/rofi/rofi-power-menu:
      url: https://github.com/jluttine/rofi-power-menu
    ~/repos/rofi/distrotube-dmenu-scripts:
      url: https://gitlab.com/dwt1/dmscripts
    ~/repos/rofi/rofi-theme-collection:
      url: https://github.com/Murzchnvok/rofi-collection

    ~/repos/polybar/polybar-scripts:
      url: https://github.com/polybar/polybar-scripts
    ~/repos/polybar/polybar-theme-collection:
      url: https://github.com/Murzchnvok/polybar-collection

    ~/repos/dotfiles_rice/cherrry9:
      url: https://github.com/cherrry9/dots
    ~/repos/dotfiles_rice/igmt-official:
      url: https://github.com/igmt-official/dotfiles
    ~/repos/dotfiles_rice/jorgeloopzz:
      url: https://github.com/jorgeloopzz/dotfiles
    ~/repos/dotfiles_rice/rose-pine-dots:
      url: https://github.com/the-argus/rose-pine-dots
    ~/repos/dotfiles_rice/misterio77-arch:
      url: https://github.com/Misterio77/Dotfiles
    ~/repos/dotfiles_rice/misterio77-nix:
      url: https://github.com/misterio77/nix-config


    ~/repos/kmonad/kmonad-contrib:
      url: https://github.com/kmonad/kmonad-contrib



    # https://hypothesis.readthedocs.io/en/latest/usage.html
    ~/repos/python/hypothesis/cdown-aur:
      url: https://github.com/cdown/aur
    ~/repos/python/hypothesis/hynek-argon2-cffi:
      url: https://github.com/hynek/argon2-cffi
    ~/repos/python/hypothesis/python-attrs-attrs:
      url: https://github.com/python-attrs/attrs
    ~/repos/python/hypothesis/Axelrod-Python-Axelrod:
      url: https://github.com/Axelrod-Python/Axelrod
    ~/repos/python/hypothesis/jab-bidict:
      url: https://github.com/jab/bidict
    ~/repos/python/hypothesis/audreyfeldroy-binaryornot:
      url: https://github.com/audreyfeldroy/binaryornot
    ~/repos/python/hypothesis/python-hyper-brotlicffi:
      url: https://github.com/python-hyper/brotlicffi
    ~/repos/python/hypothesis/pyca-cryptography:
      url: https://github.com/pyca/cryptography
    ~/repos/python/hypothesis/stratis-storage-dbus-signature-pyparsing:
      url: https://github.com/stratis-storage/dbus-signature-pyparsing
    ~/repos/python/hypothesis/dry-python-returns:
      url: https://github.com/dry-python/returns
    ~/repos/python/hypothesis/SethMMorton-fastnumbers:
      url: https://github.com/SethMMorton/fastnumbers
    ~/repos/python/hypothesis/ClusterHQ-flocker:
      url: https://github.com/ClusterHQ/flocker
    ~/repos/python/hypothesis/debsankha-flownetpy:
      url: https://github.com/debsankha/flownetpy
    ~/repos/python/hypothesis/mozilla-releng-funsize:
      url: https://github.com/mozilla-releng/funsize
    ~/repos/python/hypothesis/fusionapp-fusion-index:
      url: https://github.com/fusionapp/fusion-index
    ~/repos/python/hypothesis/python-hyper-h2:
      url: https://github.com/python-hyper/h2
    ~/repos/python/hypothesis/stratis-storage-into-dbus-python:
      url: https://github.com/stratis-storage/into-dbus-python
    ~/repos/python/hypothesis/mulkieran-justbases:
      url: https://github.com/mulkieran/justbases
    ~/repos/python/hypothesis/mulkieran-justbytes:
      url: https://github.com/mulkieran/justbytes
    ~/repos/python/hypothesis/loris-imageserver-loris:
      url: https://github.com/loris-imageserver/loris
    ~/repos/python/hypothesis/adamchainz-mariadb-dyncol:
      url: https://github.com/adamchainz/mariadb-dyncol
    ~/repos/python/hypothesis/SethMMorton-natsort:
      url: https://github.com/SethMMorton/natsort
    ~/repos/python/hypothesis/poliastro-poliastro:
      url: https://github.com/poliastro/poliastro
    ~/repos/python/hypothesis/moreati-b-prefix-all-the-doctests:
      url: https://github.com/moreati/b-prefix-all-the-doctests
    ~/repos/python/hypothesis/python-hyper-priority:
      url: https://github.com/python-hyper/priority
    ~/repos/python/hypothesis/AustinRochford-PyCEbox:
      url: https://github.com/AustinRochford/PyCEbox
    ~/repos/python/hypothesis/tobgu-pyrsistent:
      url: https://github.com/tobgu/pyrsistent
    ~/repos/python/hypothesis/webyneter-python-humble-utils:
      url: https://github.com/webyneter/python-humble-utils
    ~/repos/python/hypothesis/pyudev-pyudev:
      url: https://github.com/pyudev/pyudev
    ~/repos/python/hypothesis/qutebrowser-qutebrowser:
      url: https://github.com/qutebrowser/qutebrowser
    ~/repos/python/hypothesis/d9pouces-RubyMarshal:
      url: https://github.com/d9pouces/RubyMarshal
    ~/repos/python/hypothesis/sixty-north-segpy:
      url: https://github.com/sixty-north/segpy
    ~/repos/python/hypothesis/andsor-pysimoa:
      url: https://github.com/andsor/pysimoa
    ~/repos/python/hypothesis/cdown-srt:
      url: https://github.com/cdown/srt
    ~/repos/python/hypothesis/uber-tchannel-python:
      url: https://github.com/uber/tchannel-python
    ~/repos/python/hypothesis/pimutils-vdirsyncer:
      url: https://github.com/pimutils/vdirsyncer
    ~/repos/python/hypothesis/gsnedders-wcag-contrast-ratio:
      url: https://github.com/gsnedders/wcag-contrast-ratio
    ~/repos/python/hypothesis/KrzysiekJ-yacluster:
      url: https://github.com/KrzysiekJ/yacluster
    # ~/repos/python/hypothesis/cdown-yturl:
    # url: https://github.com/cdown/yturl
    ~/repos/python/hypothesis/zenml-io-zenml:
      url: https://github.com/zenml-io/zenml
