#!/usr/bin/env bash

# https://github.com/anishathalye/dotfiles/blob/master/install
set -e
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
dotbot -v -d "${BASEDIR}" -c .repos.conf.yaml --plugin /home/f1/dot/dotbot-git/git.py "${@}"
