# Debugging: click on X's to show parts of the bar that have errored

# icons_format = " <span size='x-large' stretch='ultraexpanded' font_family='DejaVuSansMono Nerd Font Mono'>{icon}</span> "
# icons_format = " <span size='x-large'>{icon}</span>"
[icons]
icons = "awesome6"

[icons.overrides]
backlight_1 = ""
backlight_2 = ""
backlight_3 = ""
backlight_4 = ""
backlight_5 = ""
backlight_6 = ""
backlight_7 = ""
backlight_8 = ""
backlight_9 = ""
backlight_10 = ""
backlight_11 = ""
backlight_12 = ""
backlight_13 = ""
backlight_empty = ""
backlight_full = ""
#
#
#
# [[block]]
# block = "custom"
# command = "sway_print_bar.py"
# interval = 0.5
# json = true

[[block]]
block = "custom"
command = "i3status_parse_nvidia_gpu"
interval = 0.5


[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 250
click_temp = 4900

[[block]]# # [[block]]
block = "backlight"# # block = "backlight"
device = "intel_backlight"# # device = "intel_backlight"
# icons_format = " <span size='large' stretch='ultraexpanded' font_family='DejaVuSansMono Nerd Font Mono'>{icon}</span> "


[[block]]
block = "memory"
# format_mem = "mem_used_percents.eng(1)"
format = "$icon $mem_used_percents"
# format_swap = "swap_used_percents"
interval = 30
warning_mem = 70
critical_mem = 90





[[block]]
block = "sound"
# show name, but the name has been converted into an icon using  block.mappings below
format = "$icon $output_name{ $volume|}"
show_volume_when_muted = true
# format = "$volume"
device_kind = "sink"
[block.mappings]
"alsa_output.pci-0000_00_1f.3-platform-sof_sdw.HiFi__hw_sofsoundwire_5__sink" = ""
"alsa_output.pci-0000_00_1f.3-platform-sof_sdw.HiFi__hw_sofsoundwire__sink" = ""
"alsa_output.pci-0000_00_1f.3-platform-sof_sdw.HiFi__hw_sofsoundwire_2__sink" = "ﰝ"

[[block]]
block = "sound"
format = "$icon $output_name{ $volume|$volume}"
# format = "$volume"
device_kind = "source"
show_volume_when_muted = true
max_vol = 150
[block.mappings]
"alsa_input.pci-0000_00_1f.3-platform-sof_sdw.HiFi__hw_sofsoundwire_4__source" = "" # dell xps laptop built in mic
"alsa_input.usb-Antlion_Audio_Antlion_Wireless_Microphone-00.mono-fallback" = ""



[[block]]
block = "temperature"
# format = "$min min, $max max, $average avg|"
format = "$icon $max"
interval = 10

[[block]]# # [[block]]
block = "battery"# # block = "battery"
device = "BAT0"
format = "$icon $percentage"# # format = "$percentage|N/A"
full_format = "$icon $percentage"
empty_format = "$icon $percentage"

[[block]]
block = "time"
interval = 1
[block.format]
full = "$icon %d/%m %T"
short = "$icon %R"



