#!/bin/bash
# https://github.com/FelixKratz/dotfiles


# Sketchybar Configurations - Discussions
# https://github.com/FelixKratz/SketchyBar/discussions/47
# 
# https://github.com/FelixKratz/dotfiles/blob/master/.config/sketchybar/items/spaces.sh

echo "$CONFIG_DIR"
source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

# FONT="DejaVuSansMono Nerd Font Mono"
FONT="SF Pro"

PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up the general bar appearance of the bar
bar=(
  height=23
  # color=$TRANSPARENT
  color=$BAR_COLOR
  # border_width=2
  # border_color=$BAR_BORDER_COLOR
  # shadow=off
  position=top
  sticky=on
  padding_right=10
  padding_left=10
  margin=-2


  y_offset=0
  topmost=on
)

# Setting up default values
defaults=(
    updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  # background.height=26
  # background.corner_radius=9
  # background.border_width=2
  # popup.background.border_width=2
  # popup.background.corner_radius=9
  # popup.background.border_color=$POPUP_BORDER_COLOR
  # popup.background.color=$POPUP_BACKGROUND_COLOR
  # popup.blur_radius=20
  # popup.background.shadow.drawing=on
)

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=26
  background.corner_radius=9
  background.border_width=2
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)

sketchybar --default "${defaults[@]}"

sketchybar --bar "${bar[@]}"

# add here


# source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/yabai.sh"

sketchybar --update

# /Users/f1/.config/sketchybar/update_sketchybar.mjs

echo "sketchybar configuration loaded.."
