#!/usr/bin/env bash

# if a brewfile has just been installed:
# After running this, start karabiner, skhd, yabai
# This will auto add all the locations as entries to the Security & Privacy to enable

PSDIR=$(dirname "$0") # --> script dir's parent
root="$(git -C "$PSDIR" rev-parse --show-toplevel)" # find git root from PSDIR
_symlink="$root/shared/bin/src/_symlink"

$_symlink $root/shared/config/broot ~/.config/broot
$_symlink $root/shared/config/xplr ~/.config/xplr
$_symlink "$HOME/data/Alfred" "$HOME/Library/Application Support/Alfred"
$_symlink $root/shared/config/skhd ~/.config/skhd
$_symlink $root/shared/config/kitty ~/.config/kitty
$_symlink $root/shared/config/tmux ~/.config/tmux
$_symlink $root/shared/config/starship.toml ~/.config/starship.toml
mkdir -p ~/.config/bat
$_symlink $root/shared/config/bat/config ~/.config/bat/config # this is a file
$_symlink $root/shared/config/lazygit/config.yml ~/Library/Application\ Support/lazygit/config.yml
$_symlink $root/shared/config/git/gitconfig ~/.gitconfig
$_symlink $root/shared/config/git/gitignore ~/.gitignore
$_symlink $root/shared/config/git/gitattributes ~/.gitattributes


# NOTE: only karabiner full config folder can be symlinked
# individual karabiner.json cannot be symlinked, as karabiner overwrites the karabiner.json whern adding new complex modifications, destroying the symlink
# NOTE: everytime a complex modification is edited inside assets/complex_modifications, the rule needs to be deleted and re-enabled in the GUI (does not need a restart)
$_symlink $root/osx/config/karabiner ~/.config/karabiner

# TODO: symlink all within launchd
# $_symlink "$HOME/dot/config/launchd" "$HOME/Library/LaunchAgents"

$_symlink $root/shared/config/vlc ~/.config/vlc

# VSCODE_CONFIG_DIR="$HOME/Library/Application Support/Code/User"
# mkdir -p "$VSCODE_CONFIG_DIR"
# symlink_dotfile config/vscode/keybindings.json "$VSCODE_CONFIG_DIR/keybindings.json"
# symlink_dotfile config/vscode/settings.json "$VSCODE_CONFIG_DIR/settings.json"

$_symlink $root/osx/config/yabai ~/.config/yabai

$_symlink $root/osx/config/nvim ~/.config/nvim
